### ISSUE TITLE
[Epic] Update the DG: user stories, glossary, NFRs, use cases

### ISSUE THREAD

**Issue by alphajae11** [AY2324S2-CS2103T-W11-2/tp#7]
- [x] https://github.com/AY2324S2-CS2103T-W11-2/tp/issues/9
- [x] https://github.com/AY2324S2-CS2103T-W11-2/tp/issues/10
- [x] https://github.com/AY2324S2-CS2103T-W11-2/tp/issues/11
- [x] https://github.com/AY2324S2-CS2103T-W11-2/tp/issues/12
